server:
  port: 8080
  servlet:
    context-path: /manage-web
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manage-web
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
#  gson:
#    date-format: yyyy-MM-dd HH:mm:ss
#  mvc:
#    converters:
#      # 指定gson
#      preferred-json-mapper: gson
