server:
  port: 8080
  servlet:
    context-path: /manage-web
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/manage-web
    username: root
    password: root
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
